postMerge :
  preRun: 
    command:
      - npm ci
      - npm run build
      - node test/prepare-jest.js
      
  
  subModules:          #Not to be changed
      
        
      - name: frontend      
        path : "./"
        pattern: 
          - "./test/frontend.spec.js"
        
        framework : jest
        
        preRun:
          env:
            TEST_FRONTEND: 1
          command:
            - node test/prepare-jest.js
            - export TEST_FRONTEND=1
            
        
        configFile : "./config/jest-frontend.config.js"
        nodeVersion : 17.3.1
      
        
      
        
preMerge : 
  
  subModules:          #Not to be changed
      - name: hoppscotch-cli      #Can be changed
        path : "./"
        pattern: 
          - "./packages/hoppscotch-cli/src/__tests__/**/*.*.ts"
        
        framework : jest
        postRun:
            command:
              - node --version
        
      - name: hoppscotch-js-sandbox       
        path : "./"
        pattern: 
          - "./packages/hoppscotch-js-sandbox/src/__tests__/**/*.*.ts"
        
        framework : jest
          
        postRun:
            command:
              - node --version
        configFile : "./packages/hoppscotch-js-sandbox/jest.config.js"
        
      - name: hoppscotch-app      
        path : "./"
        pattern: 
          - "./packages/hoppscotch-app/src/__tests__/**/*.*.ts"
        
        framework : jest
        
          
        postRun:
            command:
              - node --version
        configFile : "./packages/hoppscotch-app/jest.config.js"
        
  
parallelism: 2 # this will be depricated in future
version : 2.0

